version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    restart: unless-stopped
    networks:
      - app-network


  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

      
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus 
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" 
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Port par défaut de Grafana
    volumes:
      # Pour la persistance des données internes de Grafana (utilisateurs, etc.)
      - grafana_data:/var/lib/grafana
      # Monter le répertoire de provisioning des sources de données
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # Monter le répertoire de provisioning des tableaux de bord
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Monter le répertoire contenant les fichiers JSON des tableaux de bord
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin # Définir le mot de passe admin par défaut
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
