global:
  scrape_interval: 15s 
  evaluation_interval: 15s

# Configuration des scraping jobs pour Prometheus
scrape_configs:
  # Scraping des métriques de Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  # Scraping des métriques 
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' 
    static_configs:
      - targets: ['app:8080'] 
